### ISSUE TITLE
knobStore is null, and crashes

### ISSUE THREAD

**Issue by cdaringe** [storybooks/storybook-addon-knobs#72]
# problem statment

![screen shot 2016-11-04 at 4 57 23 pm](https://cloud.githubusercontent.com/assets/1003261/20025953/6ece17a6-a2b1-11e6-8952-75ad0a5d080f.png)

# discussion

it looks like `knobStore` doesn't get instantiated before it's accessed.  i looked through the docs, and i think that i'm registering then decorating the stories per the books!  any tips would be great

**Comment by cdaringe** [comment]
>  i'm registering then decorating the stories per the books

... as evidenced by the NOTES plugin rendering successfully :) _?_

**Comment by arunoda** [comment]
You should use knobs inside a story only. We setup some environment for knobs and it only available inside a story.

Here's some related issue: https://github.com/storybooks/storybook-addon-knobs/issues/57

**Comment by cdaringe** [comment]
oh i gotcha!  thanks!  works :)
