### ISSUE TITLE
Knob values are not used when user enter in Fullscreen mode

### ISSUE THREAD

**Issue by aivarsak** [storybooks/storybook-addon-knobs#74]
It might be intended functionality, I haven't looked at the code yet. 
But it would be nice if the knob values/settings would apply to story if story opened in Fullscreen mode.

**Comment by Rolandisimo** [comment]
It seems that the view gets re-rendered only the first time fullscreen is switched on. Further along, seems there are no re-renders when toggling fullscreen. Will investigate.

**Comment by roonyh** [comment]
Yep, A bug in storybook-ui was fixed so it was not re-rendering all the time. Re rendering in the first case should be fixed after todays update to react-storybook. [v.2.33.0](https://github.com/storybooks/react-storybook/blob/master/CHANGELOG.md#v2330). @aivarsak @Rolandisimo Could you try updating to react-storybook to latest?

**Comment by aivarsak** [comment]
@roonyh 👍  will check

**Comment by Rolandisimo** [comment]
@roonyh Thanks, will check!
