### ISSUE TITLE
Container styles Flex Fix

### ISSUE THREAD

**Issue by bluetidepro** [storybooks/storybook-addon-knobs#78]
I can't seem to get a local copy of `storybook-addon-knobs` to build correctly, so I'm just putting my suggestion here as an "issue." I was going to just try to PR this, but yeah, problems with building it sadly.

Would it be possible to modify some minor styling of the knobs container so that it flexes better in a panel and doesn't break panel layouts?

**Specifically...**

- Changing `width: 380,` to just `width: auto,` at https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/Panel.js#L8
- Changing `<div>` to `<div style={{width: '100%'}}>` at https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/Panel.js#L113
- Removing `maxWidth: '500px',` at https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/PropForm.js#L14

**Without the change**, here is some of the funky things happening:

 - http://bluetide.pro/RbGL/4QlTXxDv

You can see it gets caught off and doesn't scale when you adjust the panel.

**With those changes**, mentioned above, it makes the layout flex properly:

- http://bluetide.pro/wHS5/5UHnR8TV

You can see it fixes that flexing issue and works better with the layout, and doesn't cut anything off.

**Comment by arunoda** [comment]
Okay. This is great.
Could you send us a PR with these changes.
