### ISSUE TITLE
How to use with react-native?

### ISSUE THREAD

**Issue by hadfieldn** [storybooks/storybook-addon-knobs#83]
It looks like [others](https://github.com/storybooks/storybook-addon-knobs/issues/41) have had success getting knobs to work with react-native storybook, but when I include `import '@kadira/storybook-addon-knobs/register';` in my addons.js file I get the error `document is not defined` -- due to a [dependency on insert-css](https://github.com/storybooks/storybook-addon-knobs/blob/master/src/components/types/Date/index.js#L20), which [requires](https://github.com/substack/insert-css/blob/master/index.js#L14) `document`.

Is there another way to register the addon that works with react native?

**Comment by arunoda** [comment]
It's works for me without any issues.

* Just follow here for RN Storybook - https://github.com/storybooks/react-native-storybook
* Then follow this - https://github.com/storybooks/storybook-addon-knobs

**Comment by ndbroadbent** [comment]
Also if you interested in using this in the browser instead of on your device, you should check out [react-native-web](https://github.com/necolas/react-native-web). It can be tricky to set up, but it's working very well for me.

**Comment by xareelee** [comment]
Hi @ndbroadbent 

How to set up react-native-web to develop React Native components with storybook on a browser?

**Comment by Gongreg** [comment]
Hey, You can try to look into https://github.com/wix/react-native-storybook-example . It has knobs running in react-native.

**Comment by pastawoua** [comment]
@hadfieldn did you manage to get it running? I'm stuck as well on the same error when building.

**Comment by sowdri** [comment]
I'm struck here as well. Obviously there is a dependency on the 'document' which is missing in the react-native environment. Any workarounds/fixes?

**Comment by shilman** [comment]
@pastawoua @sowdri please see https://github.com/storybooks/storybook/issues/803

This repository is deprecated.

**Comment by sowdri** [comment]
@shilman Thank you for the info.
