### ISSUE TITLE
Fails to start: 

### ISSUE THREAD

**Issue by gregorskii** [storybooks/storybook-addon-knobs#97]
Hi there,

This library fails to start for me.

```
ERROR in ./~/react-onclickoutside/index.js
Module not found: Error: Cannot resolve module 'create-react-class' in /projects/Pulls/redux-starter/node_modules/react-onclickoutside
 @ ./~/react-onclickoutside/index.js 290:6-293:8
```

This worked a few days ago. Looks like `react-onclickoutside` removed the use of the library?

https://github.com/Pomax/react-onclickoutside/releases/tag/v5.11.0

https://github.com/Pomax/react-onclickoutside/pull/164

**Comment by sebastienbarre** [comment]
Seems this [has been fixed](https://github.com/Pomax/react-onclickoutside/commit/c71142d67287de1e72a7f9f90767065944f03679) on `react-onclickoutside`'s side.

**Comment by gregorskii** [comment]
Yep indeed. Thank you for looking into it!
